services:
  db:
    image: postgres:alpine
    container_name: "postgre_cliente_container"
    environment:
      POSTGRES_DB: "clienteDB"
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d clienteDB"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: romulosousa865/ms-cliente-app:latest
    container_name: clienteApp
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/clienteDB"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "password"
    ports:
      - "8081:8081"
    volumes:
      - app_data:/app/data
    networks:
      - app_network

volumes:
  postgres_data:
  app_data:

networks:
  app_network:
    external: true
